###
### .travis.yml
###

sudo: true
dist: trusty
os:
  - linux
  - osx

language: r
r:
  - release
  - devel
  - oldrel

cache: packages

before_install:
  - |
    echo "Environment:"
    env | sort
    echo
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]];
    then
      echo "pkg-config grep libsodium*:"
      pkg-config --list-all | grep [sS]odium
      echo
      PKG_CONFIG_DEBUG_SPEW=1 pkg-config --version
      echo
      echo "pkg-config libsodium: $(pkg-config --exists libsodium; echo $?)"
      if [[ $(pkg-config --exists libsodium) -ne 0 ]];
      then
        ## No APT package exists for libsodium on Ubuntu "trusty" release.
        ## Install from source.
        URL=https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
        LIBNAME=libsodium-stable
        TGZ=${LIBNAME}.tar.gz
        : ${TMPDIR:=/tmp}
        BUILDDIR=${TMPDIR}/${LIBNAME}
        (cd ${TMPDIR}; curl -fLo ${TGZ} ${URL} && tar zxf ${TGZ} && rm ${TGZ})
        (cd ${BUILDDIR}; ./configure)
        (cd ${BUILDDIR}; make)
        (cd ${BUILDDIR}; make check)
        (cd ${BUILDDIR}; sudo make install)
        rm -rf ${BUILDDIR}
      fi
      echo "pkg-config libsodium: $(pkg-config --exists libsodium; echo $?)"
      echo
      echo "pkg-config --list-all (late):"
      pkg-config --list-all | LC_COLLATE=C sort
      echo
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]];
    then
      echo "Makevars.site:"
      Rscript -e 'cat(tools::makevars_site())'
      echo

      : ${R_HOME:=$(Rscript -e 'R.home()')}

      ## Let's see the settings
      R CMD config --all
      echo

      echo "clang version: $(clang --version)"
      echo

      if [[ "${TRAVIS_R_VERSION_STRING}" == "devel" ]];
      then
        ## Packages aren't built until R release stablizes...
        URL=https://cloud.r-project.org/bin/macosx/el-capitan/contrib/r-devel/PACKAGES
        $(curl --head --fail --silent ${URL} > /dev/null 2>&1)
        if [ "$?" -ne 0 ];
        then
          ## Force package dependencies to be compiled from source
          sudo echo 'options(pkgType = "source")' >> ${R_PROFILE}
        fi
      fi

      echo "Rprofile.site:"
      test -r "${R_PROFILE}" && cat "${R_PROFILE}"
      echo
    fi

addons:
  apt:
    packages:
      - libsecret-1-dev
      - pkg-config

after_success:
  - test "${TRAVIS_R_VERSION_STRING}" = "release" && Rscript -e 'covr::codecov()'

