###
### .travis.yml
###

sudo: true
dist: trusty
os: linux

language: r
r:
  - release

cache: packages

before_install:
  - LIBNAME="libsodium-stable"
  - TGZ="${LIBNAME}.tar.gz"
  - curl -fLo /tmp/${TGZ} https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
  - tar zxf /tmp/${TGZ}
  - (cd /tmp/${LIBNAME}; ./configure; make && make check && sudo make install)

addons:
  apt:
    packages:
      - libsecret-1-dev

after_success:
  - test "$TRAVIS_R_VERSION_STRING" = "release" && Rscript -e 'covr::codecov()'

