###
### .travis.yml
###

sudo: true
dist: trusty
os: linux

language: r
r:
  - release

cache: packages

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      URL=https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
      LIBNAME=libsodium-stable
      TGZ=${LIBNAME}.tar.gz
      : ${TMPDIR:=/tmp}
      BUILDDIR=${TMPDIR}/${LIBNAME}
      (cd ${TMPDIR}; curl -fLo ${TGZ} ${URL} && tar zxf ${TGZ})
      rm ${TMPDIR}/${TGZ}
      (cd ${BUILDDIR}; ./configure)
      (cd ${BUILDDIR}; make)
      (cd ${BUILDDIR}; make check)
      (cd ${BUILDDIR}; sudo make install)
      rm -rf ${BUILDDIR}
    fi

addons:
  apt:
    packages:
      - libsecret-1-dev

after_success:
  - test "$TRAVIS_R_VERSION_STRING" = "release" && Rscript -e 'covr::codecov()'

