###
### .travis.yml
###

language: r
dist: trusty
sudo: false
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel
  - oldrel

repos:
  CRAN: https://cloud.r-project.org/

addons:
  apt:
    packages:
      - libsodium-dev
      - libsecret-1-dev

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

