###
### .travis.yml
###

sudo: true
dist: trusty
os: linux

language: r
r:
  - release

cache: packages

before_install:
  - URL=https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
  - LIBNAME=libsodium-stable
  - TGZ=${LIBNAME}.tar.gz
  - (cd /tmp; curl -fLo ${TGZ} ${URL} && tar zxf ${TGZ})
  - (cd /tmp/${LIBNAME}; ./configure; make && make check && sudo make install)

addons:
  apt:
    packages:
      - libsecret-1-dev

after_success:
  - test "$TRAVIS_R_VERSION_STRING" = "release" && Rscript -e 'covr::codecov()'

