###
### .travis.yml
###

language: r
dist: trusty
sudo: true
cache: packages

os:
  - linux
  - osx

r:
  - release
#  - devel
#  - oldrel

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      sudo add-apt-repository -y ppa:chris-lea/libsodium
#  - sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
#  - sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
      sudo apt-get install -y libsodium
      #sudo apt-get install -y libsodium-dev
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      echo "macOS $(sw_vers -productVersion)"
    fi
    

addons:
  apt:
    packages:
      - libsecret-1-dev

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

