###
### .travis.yml
###

sudo: true
dist: trusty
os:
  - linux
  - osx

language: r
r:
  - release
  - devel
  - oldrel

cache: packages

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]];
    then
      ## No APT package exists for libsodium on "trusty" distribution.
      ## Install it from source
      URL=https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
      LIBNAME=libsodium-stable
      TGZ=${LIBNAME}.tar.gz
      : ${TMPDIR:=/tmp}
      BUILDDIR=${TMPDIR}/${LIBNAME}
      (cd ${TMPDIR}; curl -fLo ${TGZ} ${URL} && tar zxf ${TGZ})
      rm ${TMPDIR}/${TGZ}
      (cd ${BUILDDIR}; ./configure)
      (cd ${BUILDDIR}; make)
      (cd ${BUILDDIR}; make check)
      (cd ${BUILDDIR}; sudo make install)
      rm -rf ${BUILDDIR}
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]];
    then
      ## Let's see the settings
      R CMD config --all

      echo
      echo "Makevars.site:"
      cat(tools::makevars_site())
      echo

      echo "clang version: $(clang --version)"
      echo

      echo "\$TRAVIS_R_VERSION_STRING: ${TRAVIS_R_VERSION_STRING}"
      echo

      if [[ "${TRAVIS_R_VERSION_STRING}" == "devel" ]];
      then
        ## Packages aren't built until R release stablizes...
        URL=https://cloud.r-project.org/bin/macosx/el-capitan/contrib/r-devel/PACKAGES
        $(curl --head --fail --silent ${URL} 2>/dev/null 1>&2)
        if [ "$?" -ne 0 ];
        then
          ## Force package dependencies to be compiled from source
          echo 'options(pkgType = "source")' >> ~/.Rprofile.site
        fi
      fi

      echo "Site Rprofile:"
      cat ~/.Rprofile.site
      echo
    fi

addons:
  apt:
    packages:
      - libsecret-1-dev

after_success:
  - test "${TRAVIS_R_VERSION_STRING}" = "release" && Rscript -e 'covr::codecov()'

