###
### .travis.yml
###

sudo: true
dist: trusty
os: linux

language: r
r:
  - release

cache: packages

before_install:
  - PREINSTALLDIR="$(pwd)"
  - cd /tmp
  - TGZ="LATEST.tar.gz"
  - curl -O https://download.libsodium.org/libsodium/releases/${TGZ}
  - tar zxf ${TGZ}
  - cd libsodium
  - ./configure
  - make && make check
  - sudo make install
  - cd $(PREINSTALLDIR)

addons:
  apt:
    packages:
      - libsecret-1-dev

after_success:
  - test "$TRAVIS_R_VERSION_STRING" = "release" && Rscript -e 'covr::codecov()'

