###
### .travis.yml
###

sudo: true
dist: trusty
os:
  - linux
  - osx

language: r
r:
  - release
  - devel
  - oldrel

cache: packages

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]];
    then
      if ! pkg-config --exists libsodium;
      then
        ## No APT package exists for Ubuntu "trusty" release.
        ## Install from source.
        URL_BASE=https://download.libsodium.org
        URL=${URL_BASE}/libsodium/releases/LATEST.tar.gz
        LIBNAME=libsodium-stable
        TGZ=${LIBNAME}.tar.gz
        : ${TMPDIR:=/tmp}
        BUILDDIR=${TMPDIR}/${LIBNAME}
        (cd ${TMPDIR}; curl -fLo ${TGZ} ${URL} && tar zxf ${TGZ} && rm ${TGZ})
        (cd ${BUILDDIR}; ./configure)
        (cd ${BUILDDIR}; make)
        (cd ${BUILDDIR}; make check)
        (cd ${BUILDDIR}; sudo make install)
        rm -rf ${BUILDDIR}
      fi
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]];
    then
      if [[ "${TRAVIS_R_VERSION_STRING}" == "devel" ]];
      then
        ## Packages aren't built until R release stablizes...
        URL_BASE=https://cloud.r-project.org
        URL=${URL_BASE}/bin/macosx/el-capitan/contrib/r-devel/PACKAGES
        if ! $(curl --head --fail --silent ${URL} > /dev/null 2>&1);
        then
          ## Force package dependencies to be compiled from source
          sudo echo 'options(pkgType = "source")' >> ${R_PROFILE}
        fi
      fi
    fi

addons:
  apt:
    packages:
      - libsecret-1-dev

after_success:
  - test "${TRAVIS_R_VERSION_STRING}" = "release" && Rscript -e 'covr::codecov()'

