###
### .travis.yml
###

language: r
dist: trusty
sudo: true
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel
  - oldrel

repos:
  CRAN: https://cloud.r-project.org/

before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium
#  - sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
#  - sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo apt-get install -y libsodium-dev

addons:
  apt:
    packages:
      - libsodium-dev
      - libsecret-1-dev

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

